name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 16
            ruby: 3.3
          - postgres: 15
            ruby: 3.2
          - postgres: 14
            ruby: 3.1
          - postgres: 13
            ruby: "3.0"
          - postgres: 12
            ruby: 2.7
          - postgres: 11
            ruby: 2.7
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres }}
          database: dexter_test
          dev-files: true
          config: |
            shared_preload_libraries = 'pg_stat_statements'
      - run: |
          cd /tmp
          curl -L https://github.com/HypoPG/hypopg/archive/1.4.0.tar.gz | tar xz
          cd hypopg-1.4.0
          make
          export PG_CONFIG=`which pg_config`
          sudo --preserve-env=PG_CONFIG make install
      - run: bundle exec rake test
